name: Call Build Workflow

on:
  workflow_dispatch:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]

jobs:
  call-build-push:
    uses: tex-corver/.github/.github/workflows/docker-build-push.yaml@master
    with:
      image_name: hello-world:v1
    secrets:
      DOCKER_USERNAME: admin
      DOCKER_PASSWORD: y9wb3N0Z3
