name: Call Build Workflow

on:
  workflow_dispatch:
  push:
    branches: [dev]
permissions:
  contents: read
  pull-requests: write
  packages: write
jobs:
  call-build-push:
    uses: tex-corver/.github/.github/workflows/docker-build-push.yaml@master
    with:
      image_name: docker/hello-world
    secrets:
      DOCKER_USERNAME: admin
      DOCKER_PASSWORD: y9wb3N0Z3
