name: Call Build Workflow

on:
  workflow_dispatch:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master]

jobs:
  call-build-push:
    uses: tex-corver/.github/.github/workflows/docker-build-push.yaml@master
    with:
      image_name: hello-world:v1
    secrets:
      DOCKER_USERNAME: admin
      DOCKER_PASSWORD: "123456"
