# .github/workflows/docker-build-push.yml
name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true


env:
  REGISTRY: artifactory-jcr.artifactory-jcr.svc:8081
  IMAGE_NAME: ${{ inputs.image_name }}

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run tests
        run: |
          echo "Running tests..."
          # Add your test commands here
          echo "Tests completed successfully"

  build-image:
    runs-on: arc-runner-set
    needs: run-test
    outputs:
      image-digest: ${{ steps.build.outputs.digest }}
      image-tag: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
      
      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          ssh: default=$HOME/.ssh/id_ed25519

  deploy-on-dev:
    runs-on: ubuntu-latest
    needs: build-image
    # environment: development
    steps:
      - name: Deploy to development
        run: |
          echo "Deploying image: ${{ needs.build-image.outputs.image-tag }}"
          echo "Image digest: ${{ needs.build-image.outputs.image-digest }}"
          # Add your deployment commands here
          # For example, update Kubernetes deployment, Docker Compose, etc.
          echo "Deployment to development completed"

  verify-deployment:
    runs-on: ubuntu-latest
    needs: deploy-on-dev
    steps:
      - name: Verify deployment
        run: |
          echo "Verifying deployment..."
          # Add health checks, smoke tests, etc.
          sleep 30
          echo "Deployment verification completed successfully"

  create-pr-to-master:
    runs-on: ubuntu-latest
    needs: [build-image, deploy-on-dev, verify-deployment]
    if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN || github.token }}
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN || github.token }}
          title: "Deploy ${{ env.IMAGE_NAME }} to production"
          body: |
            ## Deployment Summary
            
            - **Image**: ${{ needs.build-image.outputs.image-tag }}
            - **Digest**: ${{ needs.build-image.outputs.image-digest }}
            - **Branch**: ${{ github.ref_name }}
            - **Commit**: ${{ github.sha }}
            
            ## Verification
            - ✅ Tests passed
            - ✅ Image built and pushed successfully
            - ✅ Deployed to development environment
            - ✅ Deployment verification completed
            
            Ready for production deployment!
          branch: deploy/${{ github.ref_name }}-${{ github.run_number }}
          base: master
          delete-branch: true
  
