name: Common Workflow

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, ${{ inputs.message }}!"
